import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers/Providers";
import Navbar from "../components/Navbar/page";
import ParticlesBackground from "../components/ParticlesBackground";
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`relative overflow-y-auto min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
      <SpeedInsights/>
        {/* افکت ذرات در پس‌زمینه */}
        <div className="fixed inset-0 -z-1">
          <ParticlesBackground />
        </div>

        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
